### ISSUE TITLE
Cannot get basic example running

### ISSUE THREAD

**Issue by HumanWannabe** [OvidijusParsiunas/active-table#27] opened 2024-01-30 16:55 UTC
Hello,

I am trying to add active-table to my project but I get an error straight away. The installation (npm install active-table) worked fine, adding 7 packages. But as soon as I add the <active-table> component to my page, i get the following:

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\manioko\source\repos\NewUISvelte\node_modules\active-table\dist\utils\outerTableComponents\pagination\paginationInternalUtils' imported from C:\Users\manioko\source\repos\NewUISvelte\node_modules\active-table\dist\activeTable.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:226:11)
    at moduleResolve (node:internal/modules/esm/resolve:839:10)
    at defaultResolve (node:internal/modules/esm/resolve:1069:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:305:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:156:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Any idea what might be causing this? Apologies if I am missing something obvious... :/

**Comment by OvidijusParsiunas** [comment] 2024-01-30 17:27
Hi @HumanWannabe. I'm sorry you're experiencing this issue.

Based on your log I can see you are using Svelte - we have live [Svelte](https://stackblitz.com/edit/vitejs-vite-cm6j23?file=src%2FApp.svelte) and [Sveltekit](https://codesandbox.io/p/sandbox/active-table-sveltekit-forked-fy9wlf) examples which appear to work fine. Could potentially try to replicate the code used in those examples into your codebase to see if it helps. If you are still getting an error, could you potentially _Fork_ either of those examples (button on the top) to see if you can recreate the same error which should help me to debug your problem.

Other than that, if you can let me know more specific things about your app/packages/versions, browser, operating system to see if I can narrow it down. The goal for me is to see if I can replicate the problem on my computer. Thanks.

**Comment by HumanWannabe** [comment] 2024-01-30 18:07
Hello and thank you for such a swift response! 
The onilne Svelte example is where I copied my test code from in the first place. The Sveltekit example online did not work for me, giving the following error:
![image](https://github.com/OvidijusParsiunas/active-table/assets/819032/c741fe23-cfb0-4da0-9613-53326b0fb7ba)
The Svelte example does work online, but when I copy paste the code locally I get the error I posted on my first post. And this seems to be thrown within activeTable.js, not finding the paginationInternalUtils module, although this does exist in my local installation:
![image](https://github.com/OvidijusParsiunas/active-table/assets/819032/1653c724-834f-4330-85d3-e46aa5f941c7)

I'm not sure how I can try to fork the Svelte example locally on my computer. Could it be that the online example is using a different version of active-table than I got locally after installing it?

**Comment by OvidijusParsiunas** [comment] 2024-01-30 19:18
Just out of curiosity, do the example tables in www.activetable.io load fine for you. Also, what browser/OS are you using?

**Comment by HumanWannabe** [comment] 2024-01-30 19:31
I'm using windows 11 and Chrome 121 (latest). All examples in the home page, docs & examples work perfectly online. 

I have checked the framework page however, and it seems that only the Svelte one works. None of the other work, including vanilla JS!! I believe this might be due to my company firewall which can be a bit restrictive at times. I will try from my personal laptop too and let you know.

**Comment by HumanWannabe** [comment] 2024-01-30 19:37
I confirm that everything online, including all framework examples, works perfect from my personal laptop. I will now try to also install node.js/svelte to see if I can make a local test work too.

**Comment by OvidijusParsiunas** [comment] 2024-01-30 19:41
May I ask if you are using Svelte or SvelteKit locally?

**Comment by HumanWannabe** [comment] 2024-01-30 19:44
Yes, I am using Svelte locally. And I just tried it on my personal laptop and get the exact same error... :(

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'H:\work\active-table\my-app\node_modules\active-table\dist\utils\outerTableComponents\pagination\paginationInternalUtils' imported from H:\work\active-table\my-app\node_modules\active-table\dist\activeTable.js
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///H:/work/active-table/my-app/node_modules/active-table/dist/utils/outerTableComponents/pagination/paginationInternalUtils'

**Comment by HumanWannabe** [comment] 2024-01-30 19:46
Ah, wait!! I tried the SvelteKit example, and it works!! :)))

But from my work laptop I could not even open it to get the code. So this is because I have SvelteKit locally and not Svelte I guess. Sorry, I'm still quite new in this and get confused easily!

**Comment by OvidijusParsiunas** [comment] 2024-01-30 19:49
Did a little digging around and I actually had this problem a while back, but with React.
[Issue here](https://github.com/OvidijusParsiunas/active-table/issues/3)

It appears the problem is with how the files are bundled together. Now the solutions there focus on solving it for React, however it may be worth checking if anything in your configuration sticks out.

**Comment by OvidijusParsiunas** [comment] 2024-01-30 19:51
Oh lol. Yep, that would be the case 😆

**Comment by OvidijusParsiunas** [comment] 2024-01-30 19:52
CodeSandbox are also changing how they store draft Sandboxes and I will need to migrate them over the coming days, so don't worry if they don't work.

**Comment by OvidijusParsiunas** [comment] 2024-01-30 21:26
Thankyou for your kind donation. I will be closing this issue since the problem has been resolved. Feel free to create a new issue for anything else.

**Closed by OvidijusParsiunas** 2024-01-30 21:26 UTC
Labels: bug
